### ISSUE TITLE
Null Pointer Exception in validMove method

### ISSUE THREAD

**Issue by Mouse4TheTurtle** [Mouse4TheTurtle/EpicHackerMann#1]
**Need to figure out why this error is being thrown.**
```
Exception in thread "main" java.lang.NullPointerException
	at Board.validMove(Board.java:69)
	at Board.movePiece(Board.java:81)
	at Game.main(Game.java:26)
```
Error is thrown when a pawn is moved.

**Comment by Mouse4TheTurtle** [comment]
It seems to be an error in the pawn's Movement array.

**Comment by Mouse4TheTurtle** [comment]
Problem pinpointed to firstMove variable, meant to allow pawns to move 2 spaces ahead on their first move.

**Comment by Mouse4TheTurtle** [comment]
Issue combined with Issue #4
